version: '3.1'

services:
  app:
    container_name: projet-sir-22
    image: projet-sir-22
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8084:8084"
    depends_on:
      - dbmysql

  dbmysql:
    container_name: projet-sir-22-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_formation
      MYSQL_ROOT_PASSWORD: ucad2022
    volumes:
      - ./db:/var/lib/mysql
